### ISSUE TITLE
DatePicker JS error for non-standard admin folder names

### ISSUE THREAD

**Issue by CodeCommander** [DeuxHuitHuit/datetime#176]
https://github.com/DeuxHuitHuit/datetime/blob/a054fda8494d8e2770500243739b408625c2f1a5/assets/datetime.publish.js#L270

`url: Symphony.Context.get('root') + '/symphony/extension/datetime/get/',`

This line should be:

`url: Symphony.Context.get('symphony') + '/extension/datetime/get/',`

So that the plugin functions properly with differently named admin folders.

**Comment by nitriques** [comment]
Yeah thanks. Wanna send a PR ?

**Comment by wdebusschere** [comment]
👍  @CodeCommander  got the same issue, proposed fix is working.
@nitriques could this be implemented?
